'use strict';
// One renderer is shared by offline diagnostic pages and the live model studio.
function createOcctAnnotatedViewer(root,data,onSelect=()=>{}) {
const $=id=>root.getElementById?root.getElementById(id):root.querySelector(`[id="${id}"]`), NS='http://www.w3.org/2000/svg';
const svg=(tag,attrs={},text)=>{const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;};
const colors={failed:'#b52b36',passed:'#24734d',constructed:'#956512',unverified:'#956512',driving:'#315fb3',measured:'#487087',fixed:'#566a82',initial:'#566a82'};
let scene,selected=null,yaw=-Math.PI/4,pitch=-Math.atan(Math.sqrt(2)),zoom=1,pan=[0,0],width=800,height=580,center=[0,0,0],span=1,drag=null;
let gl=null,program=null,positionBuffer=null,normalBuffer=null,colorBuffer=null,triangleCount=0;
const canvas=$('surface'),overlay=$('overlay'),viewport=$('viewport');
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function initGL(){try{gl=canvas.getContext('webgl',{antialias:true,alpha:true});if(!gl)return;program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;attribute vec3 color;uniform mat3 rotation;uniform vec2 viewScale;uniform vec2 pan;varying vec3 vColor;varying vec3 vNormal;void main(){vec3 q=rotation*p;gl_Position=vec4(q.xy*viewScale+pan,-q.z*.5,1.);vNormal=rotation*n;vColor=color;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 vColor;varying vec3 vNormal;void main(){float light=.55+.45*max(dot(normalize(vNormal),normalize(vec3(.3,.4,1.))),0.);gl_FragColor=vec4(vColor*light,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));positionBuffer=gl.createBuffer();normalBuffer=gl.createBuffer();colorBuffer=gl.createBuffer();}catch(error){gl=null;console.warn('Wireframe fallback:',error.message);}}
function rotation(){if(scene?.kind==='sketch')return[1,0,0,0,1,0,0,0,1];const c=Math.cos(yaw),s=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);return[c,cp*s,sp*s,-s,cp*c,sp*c,0,-sp,cp];}
function normalized(p){return p.map((v,i)=>(v-center[i])/span);}
function project(p){const v=normalized(p),r=rotation(),x=r[0]*v[0]+r[3]*v[1]+r[6]*v[2],y=r[1]*v[0]+r[4]*v[1]+r[7]*v[2];return[width/2+(x*zoom*1.05*height/width+pan[0])*width/2,height/2-(y*zoom*1.05+pan[1])*height/2];}
function attribute(name,buffer,values){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);if(values)gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values),gl.STATIC_DRAW);const index=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(index);gl.vertexAttribPointer(index,3,gl.FLOAT,false,0,0);}
function loadMesh(){if(!gl)return;const positions=[],normals=[];for(const triangle of scene.mesh||[]){const p=triangle.points.map(normalized),a=p[1].map((x,i)=>x-p[0][i]),b=p[2].map((x,i)=>x-p[0][i]),n=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=Math.hypot(...n)||1;for(const v of p){positions.push(...v);normals.push(...n.map(x=>x/len));}}triangleCount=positions.length/3;gl.useProgram(program);attribute('p',positionBuffer,positions);attribute('n',normalBuffer,normals);meshColors();}
function meshColors(){if(!gl)return;const highlight=selected&&(selected.targets||[]).includes(scene.feature),values=[];for(const t of scene.mesh||[]){const c=highlight?[1,.66,.2]:[.7,.78,.87];for(let i=0;i<3;i++)values.push(...c);}gl.useProgram(program);attribute('color',colorBuffer,values);}
function visible(a){return a.kind==='dimension'?$('dimensions').checked:a.kind==='parameter'?true:$('constraints').checked;}
function activeTargets(){return new Set(selected?.targets||[]);}
function geometry(){const targets=activeTargets();if(scene.kind==='sketch'){for(const e of scene.entities||[]){const chosen=targets.has(e.id)||(e.point_ids||[]).some(id=>targets.has(id));const points=e.points.map(project).map(p=>p.join(',')).join(' ');overlay.append(svg('polyline',{points,class:'geometry'+(chosen?' selected':''),'data-entity':e.id,opacity:(scene.edited_profile?.length ? 0.35 : 1)}));}for(const points of scene.edited_profile||[]){overlay.append(svg('polyline',{points:points.map(project).map(p=>p.join(',')).join(' '),class:'geometry edited-profile'}));}if($('points').checked){for(const[id,p]of Object.entries(scene.points||{})){const q=project(p);overlay.append(svg('circle',{cx:q[0],cy:q[1],r:targets.has(id)?5:3,class:'point'+(targets.has(id)?' selected':''),'data-point':id}));}}}else{if(!gl){const r=rotation();const depth=p=>{const v=normalized(p);return r[2]*v[0]+r[5]*v[1]+r[8]*v[2];};const triangles=(scene.mesh||[]).map(t=>({t,z:t.points.reduce((sum,p)=>sum+depth(p),0)/3})).sort((a,b)=>a.z-b.z);for(const {t}of triangles)overlay.append(svg('polygon',{points:t.points.map(project).map(p=>p.join(',')).join(' '),fill:selected?'#edb362':'#bbcada',stroke:'none'}));}for(const points of scene.lines||[]){overlay.append(svg('polyline',{points:points.map(project).map(p=>p.join(',')).join(' '),class:'geometry'+(selected?' selected':''),opacity:gl&&triangleCount?'0.25':'1'}));}}}
function arrow(a,b,color){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<1)return;const ux=dx/len,uy=dy/len;overlay.append(svg('path',{d:`M${a[0]},${a[1]} L${b[0]},${b[1]}`,stroke:color,class:'dimension-line'}));for(const[p,s]of [[a,1],[b,-1]])overlay.append(svg('path',{d:`M${p[0]+s*ux*7-uy*3},${p[1]+s*uy*7+ux*3} L${p[0]},${p[1]} L${p[0]+s*ux*7+uy*3},${p[1]+s*uy*7-ux*3}`,stroke:color,class:'dimension-line'}));}
function annotationLayer(){const candidates=(scene.annotations||[]).filter(visible),taken=[];for(const a of candidates){if(!a.anchors?.length)continue;if(a.kind==='parameter'&&selected?.id!==a.id)continue;if(candidates.length>120&&selected?.id!==a.id&&a.status!=='failed')continue;const q=a.anchors.map(project),color=colors[a.status]||'#53657c';if(a.detail?.dimension_paths?.length){for(const path of a.detail.dimension_paths)overlay.append(svg('polyline',{points:path.map(project).map(p=>p.join(',')).join(' '),stroke:color,class:'dimension-line route-dimension','data-route':a.id}));}else if(a.detail?.angular_arc?.length){overlay.append(svg('polyline',{points:a.detail.angular_arc.map(project).map(p=>p.join(',')).join(' '),stroke:color,class:'dimension-line angular-dimension'}));}else if(a.kind==='dimension'&&q.length>=2)arrow(q[0],q[1],color);if($('points').checked&&a.kind==='requirement'&&a.status==='failed'){for(const p of q)overlay.append(svg('circle',{cx:p[0],cy:p[1],r:5,class:'witness'}));}let x=q.reduce((n,p)=>n+p[0],0)/q.length,y=q.reduce((n,p)=>n+p[1],0)/q.length;const label=a.label.replace(/(\d+\.\d{3})\d+/g,'$1'),w=Math.min(320,Math.max(30,label.length*6.5+14));let shift=0;while(taken.some(r=>Math.abs(x-r.x)<(w+r.w)/2&&Math.abs(y-18-shift-r.y)<24)&&shift<160)shift+=25;x=Math.max(w/2+6,Math.min(width-w/2-6,x));y=Math.max(16,Math.min(height-16,y-18-shift));taken.push({x,y,w});if(shift)overlay.append(svg('path',{d:`M${q[0][0]},${q[0][1]} L${x},${y}`,stroke:color,fill:'none',opacity:.4}));const group=svg('g',{class:'anno '+a.status+(selected?.id===a.id?' selected':''),transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-label':`${a.label}: ${a.status}`,'data-annotation':a.id,style:`color:${color}`});group.append(svg('rect',{x:-w/2,y:-12,width:w,height:24,rx:4}),svg('text',{'text-anchor':'middle',x:0,y:0},label.length>48?label.slice(0,45)+'…':label));group.addEventListener('click',e=>{e.stopPropagation();select(a);});group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(a);}});overlay.append(group);}}
function draw(){width=viewport.clientWidth;height=viewport.clientHeight;const ratio=window.devicePixelRatio||1;canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);overlay.setAttribute('viewBox',`0 0 ${width} ${height}`);overlay.replaceChildren();if(gl){gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(scene.kind==='solid'&&triangleCount){gl.useProgram(program);gl.enable(gl.DEPTH_TEST);attribute('p',positionBuffer);attribute('n',normalBuffer);attribute('color',colorBuffer);gl.uniformMatrix3fv(gl.getUniformLocation(program,'rotation'),false,new Float32Array(rotation()));gl.uniform2f(gl.getUniformLocation(program,'viewScale'),zoom*1.05*height/width,zoom*1.05);gl.uniform2f(gl.getUniformLocation(program,'pan'),...pan);gl.drawArrays(gl.TRIANGLES,0,triangleCount);}}geometry();annotationLayer();}
function list(){const filter=$('filter').value.toLowerCase();$('annotations').replaceChildren();for(const a of scene.annotations||[]){if(filter&&!`${a.label} ${a.kind} ${a.id}`.toLowerCase().includes(filter))continue;const button=document.createElement('button');button.className='annotation-row '+a.status+(selected?.id===a.id?' selected':'');button.dataset.annotation=a.id;const label=document.createElement('span');label.textContent=a.label;const status=document.createElement('small');status.textContent=a.status;button.append(label,status);button.addEventListener('click',()=>select(a));$('annotations').append(button);}$('annotation-count').textContent=`(${scene.annotations?.length||0})`;}
function quantity(v){if(!v)return 'unavailable';const units={millimeter:'mm',centimeter:'cm',meter:'m',inch:'in',Millimeter:'mm',CubicMillimeter:'mm³',Radian:'rad',Kilogram:'kg',Count:''};if(v.scalar)return quantity(v.scalar);if(v.vector)return `(${quantity(v.vector.x)}, ${quantity(v.vector.y)}, ${quantity(v.vector.z)})`;if(v.value!==undefined)return `${Number(v.value).toLocaleString('en-US',{maximumSignificantDigits:6})} ${units[v.unit]||''}`.trim();return String(v.integer??v.boolean??v.choice??'unavailable');}
function select(a){selected=a;list();$('selection').replaceChildren();const heading=document.createElement('h3');heading.textContent=a.label;$('selection').append(heading);const description=document.createElement('p');description.textContent=`${a.kind} · ${a.status}. Linked geometry: ${(a.targets||[]).join(', ')||'none'}.`;$('selection').append(description);for(const name of a.parameters||[]){const p=document.createElement('p');p.textContent=`Parameter ${name}: ${quantity(scene.parameters?.[name]?.value)}`;$('selection').append(p);}const d=a.detail,info=document.createElement('p');if(d.measured_mm!==undefined)info.textContent=`Measured extent: ${quantity({value:d.measured_mm,unit:'Millimeter'})}. This is a geometry measurement.`;else if(d.max_residual!==undefined&&d.max_residual!==null)info.textContent=`Residual ${d.max_residual.toExponential(3)} ${d.residual_unit}; solver tolerance ${d.tolerance}.`;else if(d.by_construction)info.textContent='Tangency is imposed during native curve construction; no solver residual is claimed.';else if(d.verification){const v=d.verification;info.textContent=[v.message,v.measured?`Measured ${quantity(v.measured)}`:'',v.evidence?`Evidence: ${v.evidence.kind}`:''].filter(Boolean).join(' · ');}else if(d.value_mm!==undefined)info.textContent=`Driving definition: ${quantity({value:d.value_mm,unit:'Millimeter'})}.`;else if(d.value)info.textContent=`Driving definition: ${quantity(d.value)}.`;else info.textContent=d.description||'';$('selection').append(info);const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Model references and solver evidence';const pre=document.createElement('pre');pre.textContent=JSON.stringify(a.detail,null,2);details.append(summary,pre);$('selection').append(details);meshColors();draw();onSelect(a,scene);}
function fit(){zoom=1;pan=[0,0];yaw=-Math.PI/4;pitch=-Math.atan(Math.sqrt(2));draw();}
function choose(index){scene=data.scenes[index];selected=null;const b=scene.bounds||[[-1,-1,-1],[1,1,1]];center=b[0].map((v,i)=>v*.5+b[1][i]*.5);span=Math.max(...b[1].map((v,i)=>v-b[0][i]),1e-12);$('coordinates').textContent=scene.coordinate_system||'family-local millimeters';$('empty').textContent=scene.error||scene.profile_error||'';$('selection').textContent='Choose an annotation in the view or list.';const failed=(scene.annotations||[]).filter(a=>a.status==='failed').length,unverified=(scene.annotations||[]).filter(a=>a.status==='unverified').length;const solver=scene.solver;$('status').className=failed||scene.error||scene.profile_error||solver&&!solver.solved?'failed':'';$('status').textContent=scene.profile_error?`Profile edit failed: ${scene.profile_error}`:scene.error?`Geometry unavailable: ${scene.error}`:solver?`${solver.solved?'Sketch solved':'Conflicting sketch constraints'} · ${solver.free_degrees} free degrees · ${solver.redundant_equations} redundant equations · maximum residual ${solver.max_residual.toExponential(3)}`:`${failed} unmet checks · ${unverified} unverified checks · measured overall spans and linked driving values · ${gl?'solid rendering':'software surface rendering'}`;$('summary').textContent=(data.accepted===false?'Rejected edit · ':'')+scene.title;loadMesh();list();fit();}
viewport.addEventListener('pointerdown',e=>{if(e.target.closest?.('.anno'))return;drag={x:e.clientX,y:e.clientY};viewport.setPointerCapture(e.pointerId);});viewport.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(scene.kind==='solid'){yaw+=dx*.01;pitch=Math.max(-1.5,Math.min(1.5,pitch+dy*.01));}else{pan[0]+=dx/width*2;pan[1]-=dy/height*2;}drag={x:e.clientX,y:e.clientY};draw();});viewport.addEventListener('pointerup',()=>drag=null);viewport.addEventListener('pointercancel',()=>drag=null);viewport.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.1,Math.min(30,zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});viewport.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;$('selection').textContent='Choose an annotation in the view or list.';meshColors();list();draw();}if(e.key==='Home'){e.preventDefault();fit();}});
for(const id of ['dimensions','constraints','points'])$(id).addEventListener('change',draw);$('fit').addEventListener('click',fit);$('filter').addEventListener('input',list);$('scene').addEventListener('change',()=>choose(Number($('scene').value)));const observer=new ResizeObserver(()=>draw());observer.observe(viewport);
for(let i=0;i<data.scenes.length;i++){const option=document.createElement('option');option.value=String(i);option.textContent=`${data.scenes[i].kind==='sketch'?'Sketch':'3D'} · ${data.scenes[i].title}`;$('scene').append(option);}initGL();const initial=Math.max(0,data.scenes.findIndex(s=>!s.error));$('scene').value=String(initial);choose(initial);
const viewer={get data(){return data;},selectAnnotation:id=>{const a=scene.annotations.find(a=>a.id===id);if(a)select(a);},get selected(){return selected?.id;},get scene(){return scene;},get camera(){return {yaw,pitch,zoom,pan:[...pan]};},project,fit,
  update(next){const previous=scene&&[scene.kind,scene.instance,scene.feature],selection=selected?.id,view={yaw,pitch,zoom,pan:[...pan]};data=next;$('scene').replaceChildren();for(let i=0;i<data.scenes.length;i++){const option=document.createElement('option');option.value=String(i);option.textContent=`${data.scenes[i].kind==='sketch'?'Sketch':'3D'} · ${data.scenes[i].title}`;$('scene').append(option);}let index=data.scenes.findIndex(s=>previous&&s.kind===previous[0]&&s.instance===previous[1]&&s.feature===previous[2]);const same=index>=0&&!data.scenes[index].error;if(!same)index=Math.max(0,data.scenes.findIndex(s=>!s.error));$('scene').value=String(index);choose(index);if(same){({yaw,pitch,zoom,pan}=view);if(selection){const a=scene.annotations.find(a=>a.id===selection);if(a){selected=a;select(a);}}draw();}},
  destroy(){observer.disconnect();if(gl){for(const buffer of [positionBuffer,normalBuffer,colorBuffer])gl.deleteBuffer(buffer);gl.deleteProgram(program);}}
};return viewer;
}
window.createOcctAnnotatedViewer=createOcctAnnotatedViewer;
if(document.getElementById('view-data'))window.occtViewer=createOcctAnnotatedViewer(document,JSON.parse(document.getElementById('view-data').textContent));
